FROM golang:1.22.1 AS builder

WORKDIR /app
COPY . .
RUN go mod download && \
    CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go install github.com/mattn/go-sqlite3 && \
    CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -o ./app_windows.exe ./cmd

FROM ubuntu:latest

WORKDIR /app
COPY --from=builder /app/app_windows.exe /app/app_windows.exe
COPY config /app/config
COPY web /app/web
VOLUME /app/db

CMD ["/app/app_windows.exe"]